// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/Pyrki4/go-shop/internal/config"
	"github.com/Pyrki4/go-shop/internal/db"
	"github.com/Pyrki4/go-shop/internal/handlers"
	"github.com/Pyrki4/go-shop/internal/repositories"
	"github.com/Pyrki4/go-shop/internal/services"
)

// Injectors from wire.go:

func InitializeContainer() (*handlers.ProductHandler, error) {
	configConfig := config.Load()
	gormDB, err := db.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	productRepository := repositories.NewProductRepository(gormDB)
	productService := services.NewProductService(productRepository)
	productHandler := handlers.NewProductHandler(productService)
	return productHandler, nil
}
